### ISSUE TITLE
swift3 support?

### ISSUE THREAD

**Issue by philippeluickx** [andresinaka/SwiftCop#5]
Hey! Great library, would love to see swift3 supported.

Thanks!

**Comment by andresinaka** [comment]
Yes, it's in my todo. I'll work no that tomorrow for sure!

**Comment by philippeluickx** [comment]
Awesome, you rock!

**Comment by andresinaka** [comment]
@philippeluickx done! sorry for the delay I've been kind of busy !

Master is now Swift 3.0 and updated pod version to 1.0.

**Comment by philippeluickx** [comment]
You're a hero! Thanks a lot!
